### ISSUE TITLE
HTTP Server Panic

### ISSUE THREAD

**Issue by hekaldama** [yp-engineering/rbd-docker-plugin#3]
This is driver.go func rbdImageIsLocked 

```
 rbd-volume-plugin: 2015/07/27 12:37:38 main.go:44: Setting up Ceph Driver for PluginID=rbd, pool=rbd, user=admin, root=/var/lib/docker/volumes
  rbd-volume-plugin: 2015/07/27 12:37:38 driver.go:67: newCephRBDVolumeDriver: setting base mount dir=/var/lib/docker/volumes/rbd/rbd
  rbd-volume-plugin: 2015/07/27 12:37:38 main.go:47: Creating Docker VolumeDriver Handler
  rbd-volume-plugin: 2015/07/27 12:37:38 main.go:52: Opening Socket for Docker to connect: /usr/share/docker/plugins/rbd.sock
  rbd-volume-plugin: 2015/07/27 12:37:44 driver.go:142: Create(foo)
  rbd-volume-plugin: 2015/07/27 12:37:45 driver.go:283: Path request(foo) => /var/lib/docker/volumes/rbd/rbd/foo
  rbd-volume-plugin: 2015/07/27 12:37:45 driver.go:283: Path request(foo) => /var/lib/docker/volumes/rbd/rbd/foo
  rbd-volume-plugin: 2015/07/27 12:37:45 driver.go:214: Mount(foo)
  rbd-volume-plugin: 2015/07/27 12:37:45 server.go:1775: http: panic serving @: runtime error: index out of range
  goroutine 5 [running]:
  net/http.func·011()
   /usr/local/go/src/net/http/server.go:1130 +0xbb
  github.com/noahdesu/go-ceph/rbd.(*Image).ListLockers(0xc208073898, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
   /go/src/github.com/noahdesu/go-ceph/rbd/rbd.go:521 +0x655
  main.(*cephRBDVolumeDriver).rbdImageIsLocked(0xc208044410, 0xc20800abd0, 0x3, 0xc20803d300, 0x0, 0x0)
   /go/src/github.com/yp-engineering/rbd-docker-plugin/driver.go:388 +0x513
  main.cephRBDVolumeDriver.Mount(0xc208020560, 0x1f, 0x71f070, 0x3, 0x719a70, 0x5, 0xc20803cba0, 0xc20800a990, 0xc20803a020, 0xc20803a028, ...)
   /go/src/github.com/yp-engineering/rbd-docker-plugin/driver.go:220 +0x1d1
  main.(*cephRBDVolumeDriver).Mount(0xc208044370, 0xc20800abd0, 0x3, 0x0, 0x0, 0x0, 0x0)
   <autogenerated>:3 +0xd7
  github.com/calavera/dkvolume.func·005(0xc20800abd0, 0x3, 0x0, 0x0, 0x0, 0x0)
   /go/src/github.com/calavera/dkvolume/api.go:84 +0x62 
  github.com/calavera/dkvolume.func·007(0x7fa739c0c1f0, 0xc20805c500, 0xc208034dd0)
   /go/src/github.com/calavera/dkvolume/api.go:99 +0xac
  net/http.HandlerFunc.ServeHTTP(0xc20800aa30, 0x7fa739c0c1f0, 0xc20805c500, 0xc208034dd0)
   /usr/local/go/src/net/http/server.go:1265 +0x41
  net/http.(*ServeMux).ServeHTTP(0xc20803cc30, 0x7fa739c0c1f0, 0xc20805c500, 0xc208034dd0)
   /usr/local/go/src/net/http/server.go:1541 +0x17d
  net/http.serverHandler.ServeHTTP(0xc208046180, 0x7fa739c0c1f0, 0xc20805c500, 0xc208034dd0)
   /usr/local/go/src/net/http/server.go:1703 +0x19a
  net/http.(*conn).serve(0xc20805c280)
   /usr/local/go/src/net/http/server.go:1204 +0xb57
  created by net/http.(*Server).Serve
   /usr/local/go/src/net/http/server.go:1751 +0x35e
 rbd-volume-plugin: 2015/07/27 12:38:00 driver.go:300: Unmount(foo)
 rbd-volume-plugin: 2015/07/27 12:38:00 driver.go:309: Volume is not in known mounts: foo
```

**Comment by porcupie** [comment]
Hmm - This is using ListLockers from the go-ceph library, which I thought I had commented out as broken / causes panics a long time ago - can you verify which version you have ?  Might have been an error porting over code to github.

**Comment by hekaldama** [comment]
@porcupie I just pulled this out of a comment in the code. See d02e3b3194. Feel free to close if invalid.

**Comment by porcupie** [comment]
OK no problem.  Let's keep it on the radar in case we want to submit as a bug to go-ceph library.
